// eslint-disable-next-line import/no-anonymous-default-export
export default {
  code: 'editor-code',
  codeHighlight: {
    atrule: 'editor__tokenAttr',
    attr: 'editor__tokenAttr',
    boolean: 'editor__tokenProperty',
    builtin: 'editor__tokenSelector',
    cdata: 'editor__tokenComment',
    char: 'editor__tokenSelector',
    class: 'editor__tokenFunction',
    'class-name': 'editor__tokenFunction',
    comment: 'editor__tokenComment',
    constant: 'editor__tokenProperty',
    deleted: 'editor__tokenProperty',
    doctype: 'editor__tokenComment',
    entity: 'editor__tokenOperator',
    function: 'editor__tokenFunction',
    important: 'editor__tokenVariable',
    inserted: 'editor__tokenSelector',
    keyword: 'editor__tokenAttr',
    namespace: 'editor__tokenVariable',
    number: 'editor__tokenProperty',
    operator: 'editor__tokenOperator',
    prolog: 'editor__tokenComment',
    property: 'editor__tokenProperty',
    punctuation: 'editor__tokenPunctuation',
    regex: 'editor__tokenVariable',
    selector: 'editor__tokenSelector',
    string: 'editor__tokenSelector',
    symbol: 'editor__tokenProperty',
    tag: 'editor__tokenProperty',
    url: 'editor__tokenOperator',
    variable: 'editor__tokenVariable',
  },
  embedBlock: {
    base: 'editor__embedBlock',
    focus: 'editor__embedBlockFocus',
  },
  heading: {
    h1: 'editor-heading-h1',
    h2: 'editor-heading-h2',
    h3: 'editor-heading-h3',
    h4: 'editor-heading-h4',
    h5: 'editor-heading-h5',
  },
  mark: 'editor__mark',
  markOverlap: 'editor__markOverlap',
  image: 'editor-image',
  link: 'editor-link',
  list: {
    checklist: 'editor__checklist',
    listitem: 'editor__listItem',
    listitemChecked: 'editor__listItemChecked',
    listitemUnchecked: 'editor__listItemUnchecked',
    nested: {
      listitem: 'editor__nestedListItem',
    },
    olDepth: [
      'editor__ol1',
      'editor__ol2',
      'editor__ol3',
      'editor__ol4',
      'editor__ol5',
    ],
    ul: 'editor__ul',
  },
  ltr: 'ltr',
  paragraph: 'editor-paragraph',
  placeholder: 'editor-placeholder',
  quote: 'editor-quote',
  rtl: 'rtl',
  text: {
    bold: 'editor-text-bold',
    code: 'editor-text-code',
    hashtag: 'editor-text-hashtag',
    italic: 'editor-text-italic',
    overflowed: 'editor-text-overflowed',
    strikethrough: 'editor-text-strikethrough',
    underline: 'editor-text-underline',
    underlineStrikethrough: 'editor-text-underlineStrikethrough',
  },
  table: 'editor__table',
  tableCell: 'editor__tableCell',
  tableCellActionButton: 'editor__tableCellActionButton',
  tableCellActionButtonContainer:
    'editor__tableCellActionButtonContainer',
  tableCellEditing: 'editor__tableCellEditing',
  tableCellHeader: 'editor__tableCellHeader',
  tableCellPrimarySelected: 'editor__tableCellPrimarySelected',
  tableCellResizer: 'editor__tableCellResizer',
  tableCellSelected: 'editor__tableCellSelected',
  tableCellSortedIndicator: 'editor__tableCellSortedIndicator',
  tableResizeRuler: 'editor__tableCellResizeRuler',
  tableRowStriping: 'editor__tableRowStriping',
  tableSelected: 'editor__tableSelected',
  tableSelection: 'editor__tableSelection',
};
